spring:
  profiles:
    active: development
---
spring:
  profiles: development
  redis:
    host: 192.168.1.128
    port: 6379
  datasource:
    url: jdbc:mysql://192.168.1.120:3306/catalogdb
    username: root
    password: 3g2win.com
    initialize: true
    
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.128:8761/eureka/
---
spring:
  profiles: docker
  redis:
    host: redis
    port: 6379
  datasource:
    url: jdbc:mysql://mysql:3306/dev4?useSSL=false
    username: root
    password: dbpass
    initialize: true
  zipkin:
      base-url: http://zipkin:9411/
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test
  redis:
    host: localhost
    port: 6379
  jpa:
    database: H2
  datasource:
    initialize: false